// ARIA M&A Intelligence Platform — Privacy Policy content
// Effective: 2026-04-20 | Last updated: 2026-04-20
// DRAFT — for counsel review before publication

export const PRIVACY_EFFECTIVE = "2026-04-20";
export const PRIVACY_LAST_UPDATED = "2026-04-20";
export const PRIVACY_VERSION = "v2026-04-20";

export const dataCategories = [
  {
    category: "Account & Identity",
    examples: "Name, work email, job title, company name, phone number",
    source: "Provided by you at registration or profile update",
  },
  {
    category: "Authentication",
    examples: "Hashed passwords, SSO tokens, session identifiers, MFA status",
    source: "Generated by the Service during authentication",
  },
  {
    category: "Customer Data (Deal Data)",
    examples: "CIMs, financial models, data room documents, target lists, deal notes, AI-generated outputs",
    source: "Uploaded or generated by you within the Service",
  },
  {
    category: "Usage & Interaction",
    examples: "Pages visited, features used, queries submitted, clicks, timestamps",
    source: "Collected automatically as you use the Service",
  },
  {
    category: "Device & Technical",
    examples: "IP address, browser type, OS, screen resolution, referring URL",
    source: "Collected automatically by our servers and analytics tools",
  },
  {
    category: "Communications",
    examples: "Emails, support tickets, demo requests, feedback submissions",
    source: "Provided by you when contacting us",
  },
  {
    category: "Billing & Payment",
    examples: "Billing name, billing address, last 4 digits of card, invoice history",
    source: "Provided by you; payment details processed by our payment processor",
  },
  {
    category: "Cookies & Tracking",
    examples: "Session cookies, preference cookies, analytics identifiers, consent records",
    source: "Set by us or third-party tools with your consent where required",
  },
];

export const retentionTable = [
  {
    category: "Account & Identity",
    retention: "Duration of account + [FILL: e.g., 90 days] after deletion",
    justification: "Needed to provide the Service and comply with legal obligations",
  },
  {
    category: "Customer Data (Deal Data)",
    retention: "[FILL: e.g., 30 days] after subscription ends or account deletion",
    justification: "Allows data export; deleted thereafter unless legally required to retain",
  },
  {
    category: "Usage & Interaction",
    retention: "[FILL: e.g., 13 months] rolling",
    justification: "Service improvement, security monitoring, and aggregate analytics",
  },
  {
    category: "Device & Technical",
    retention: "[FILL: e.g., 13 months] rolling",
    justification: "Security, fraud prevention, and debugging",
  },
  {
    category: "Communications",
    retention: "[FILL: e.g., 3 years] from last interaction",
    justification: "Support quality, legal record-keeping",
  },
  {
    category: "Billing & Payment",
    retention: "[FILL: e.g., 7 years] from transaction",
    justification: "Tax and accounting obligations",
  },
  {
    category: "Cookies & Tracking",
    retention: "See Cookie table; consent records retained [FILL: e.g., 3 years]",
    justification: "Demonstrating consent under GDPR/ePrivacy",
  },
];

export const cookieTable = [
  {
    category: "Strictly Necessary",
    provider: "ARIA (first-party)",
    retention: "Session / up to 1 year",
    purpose: "Authentication, security, session management",
    optOut: "Cannot be disabled — required for the Service to function",
  },
  {
    category: "Functional / Preferences",
    provider: "ARIA (first-party)",
    retention: "Up to 1 year",
    purpose: "Remembering your language, theme, and UI preferences",
    optOut: "Can be disabled; may affect user experience",
  },
  {
    category: "Analytics",
    provider: "[FILL: e.g., Plausible, Mixpanel]",
    retention: "[FILL: e.g., 13 months]",
    purpose: "Understanding how users navigate the Service to improve it",
    optOut: "Opt out via Cookie Preferences or Global Privacy Control",
  },
  {
    category: "Marketing / Retargeting",
    provider: "[FILL: e.g., LinkedIn Insight Tag, Google Ads]",
    retention: "[FILL: e.g., 90 days]",
    purpose: "Measuring campaign effectiveness; retargeting on third-party platforms",
    optOut: "Opt out via Cookie Preferences; not set without consent",
  },
];

export const rightsTable = [
  {
    right: "Access / Know",
    euUk: "✓ Art. 15 GDPR",
    usStates: "✓ CCPA / CPRA + state laws",
    canada: "✓ PIPEDA / Law 25",
    brazil: "✓ LGPD Art. 18",
    apac: "✓ Singapore PDPA / AU Privacy Act",
    howToExercise: "Submit request at /legal/privacy#rights or email [FILL: privacy email]",
  },
  {
    right: "Correction / Rectification",
    euUk: "✓ Art. 16 GDPR",
    usStates: "✓ CPRA + some state laws",
    canada: "✓ PIPEDA",
    brazil: "✓ LGPD Art. 18",
    apac: "✓ Singapore PDPA / AU Privacy Act",
    howToExercise: "Update in account settings or submit request",
  },
  {
    right: "Deletion / Erasure",
    euUk: "✓ Art. 17 GDPR",
    usStates: "✓ CCPA / CPRA + state laws",
    canada: "Limited (PIPEDA)",
    brazil: "✓ LGPD Art. 18",
    apac: "Limited",
    howToExercise: "Submit deletion request; we respond within 30 days",
  },
  {
    right: "Portability",
    euUk: "✓ Art. 20 GDPR",
    usStates: "✓ CPRA",
    canada: "Limited",
    brazil: "✓ LGPD Art. 18",
    apac: "Limited",
    howToExercise: "Export via account settings (CSV, JSON, PDF)",
  },
  {
    right: "Object / Opt Out",
    euUk: "✓ Art. 21 GDPR",
    usStates: "✓ Do Not Sell/Share (CCPA); GPC honored",
    canada: "✓ PIPEDA",
    brazil: "✓ LGPD",
    apac: "✓ Singapore PDPA",
    howToExercise: "Cookie Preferences; GPC signal honored automatically",
  },
  {
    right: "Restrict Processing",
    euUk: "✓ Art. 18 GDPR",
    usStates: "Limited",
    canada: "Limited",
    brazil: "✓ LGPD",
    apac: "Limited",
    howToExercise: "Submit request; we will confirm within 30 days",
  },
  {
    right: "Withdraw Consent",
    euUk: "✓ Art. 7(3) GDPR",
    usStates: "✓ where consent is the basis",
    canada: "✓ PIPEDA",
    brazil: "✓ LGPD",
    apac: "✓",
    howToExercise: "Cookie Preferences; contact [FILL: privacy email]",
  },
  {
    right: "Non-Discrimination",
    euUk: "N/A (GDPR does not include this right)",
    usStates: "✓ CCPA § 1798.125",
    canada: "N/A",
    brazil: "N/A",
    apac: "N/A",
    howToExercise: "We do not discriminate for exercising privacy rights",
  },
];

export const privacySections = [
  {
    id: "summary",
    title: "Plain-English Summary",
    anchor: "summary",
    inShort: "What we collect, why, who sees it, and your rights — in four sentences.",
    body: `We collect information you give us (like your name and work email), information generated by your use of the Service (like deal documents and usage logs), and technical information from your device (like your IP address). We use this information to provide and improve ARIA, communicate with you, and comply with legal obligations. We do not sell your personal data. We do not use your deal data to train AI models. You have rights over your data — including the right to access, correct, delete, and export it — and we make those rights easy to exercise.`,
  },
  {
    id: "who-we-are",
    title: "Who We Are and How to Contact Us",
    anchor: "who-we-are",
    inShort: "We are [FILL: legal entity name]. Here is how to reach our privacy team.",
    body: `**Data controller.** [FILL: legal entity name] ("ARIA," "we," "us," or "our") is the data controller for personal data processed in connection with the Service. Our registered address is [FILL: registered address].

**Privacy contact.** For privacy inquiries, data subject requests, or to contact our Data Protection Officer (if applicable), please write to: [FILL: privacy/DPO email] or [FILL: postal address, Attn: Privacy].

**EU representative.** [FILL: If ARIA has no EU establishment but processes EU personal data, name the Article 27 representative here, or state "We are in the process of appointing an EU representative."]

**UK representative.** [FILL: Same for UK GDPR Article 27 representative.]

**Response time.** We aim to respond to all privacy inquiries within 30 days. For complex requests, we may extend this by up to 60 days and will notify you.`,
  },
  {
    id: "what-we-collect",
    title: "What We Collect",
    anchor: "what-we-collect",
    inShort: "We collect what you give us, what the Service generates, and basic technical data from your device.",
    body: `The table below summarizes the categories of personal data we collect. "Personal data" means any information that identifies or can reasonably identify a natural person.`,
    table: "dataCategories",
  },
  {
    id: "why-we-collect",
    title: "Why We Collect It — Lawful Bases and Purpose Mapping",
    anchor: "why-we-collect",
    inShort: "We collect data to run the Service, keep it secure, communicate with you, and meet legal obligations.",
    body: `We process personal data only when we have a lawful basis to do so. Under GDPR and equivalent laws, our lawful bases are:

**Contract performance (GDPR Art. 6(1)(b)).** We process account, authentication, and billing data to fulfill our contract with you — to create your account, provide the Service, and process payments.

**Legitimate interests (GDPR Art. 6(1)(f)).** We process usage, device, and technical data to improve the Service, detect and prevent fraud and security threats, and conduct aggregate analytics. We have assessed that our legitimate interests are not overridden by your rights and interests.

**Consent (GDPR Art. 6(1)(a)).** We process analytics and marketing cookies only with your consent, which you can withdraw at any time via Cookie Preferences.

**Legal obligation (GDPR Art. 6(1)(c)).** We process billing and communication data to comply with tax, accounting, and regulatory requirements.

**For US state privacy laws (CCPA/CPRA and equivalents).** We process personal data for the following business purposes: providing and improving the Service, security and fraud prevention, customer support, legal compliance, and aggregate analytics. We do not sell personal data. We do not share personal data for cross-context behavioral advertising without your opt-in consent.`,
  },
  {
    id: "ai-and-data",
    title: "AI and Your Data",
    anchor: "ai-and-data",
    inShort: "Your deal data does not train our AI models. Inputs and outputs are retained only as long as needed to provide the Service.",
    body: `**No training on Customer Data.** We do not use your Customer Data (deal documents, financial models, CIMs, target lists, or AI-generated outputs) to train, fine-tune, or improve foundation AI models. Your deal data is used solely to provide the Service to you.

**Prompt and output retention.** Queries you submit to ARIA's AI agents and the outputs they produce are retained for [FILL: e.g., 90 days] to enable you to review, export, and audit your work. After that period, they are deleted unless you have saved them within the Service.

**Human review.** Our team may review a small, anonymized sample of AI interactions to evaluate output quality and safety. Any such review is conducted under strict confidentiality controls and does not involve access to identifiable Customer Data without your consent.

**EU AI Act transparency.** ARIA uses AI systems that are subject to the EU AI Act. We maintain logs of AI-generated outputs, including the agent, model version, timestamp, and source references. These logs are available to you on request for audit purposes.

**No fully automated decisions.** We do not make fully automated decisions about individuals that produce legal or similarly significant effects, as defined in GDPR Article 22. All significant outputs are intended for human review.`,
  },
  {
    id: "cookies",
    title: "Cookies and Similar Technologies",
    anchor: "cookies",
    inShort: "We use strictly necessary cookies to run the Service, and optional analytics and marketing cookies only with your consent.",
    body: `We use cookies and similar technologies (such as local storage and pixel tags) on our website and within the Service. The table below describes each category.

You can manage your cookie preferences at any time by clicking "Cookie Preferences" in the footer of any page. If your browser or device sends a Global Privacy Control (GPC) signal, we treat it as an opt-out of analytics and marketing cookies.`,
    table: "cookieTable",
  },
  {
    id: "sharing",
    title: "Sharing and Sub-Processors",
    anchor: "sharing",
    inShort: "We share data only with service providers who help us run ARIA, and only as necessary.",
    body: `We do not sell personal data. We share personal data with third parties only in the following circumstances:

**Sub-processors.** We use third-party service providers ("sub-processors") to help us provide the Service — for example, cloud infrastructure, payment processing, email delivery, and analytics. Each sub-processor is bound by a data processing agreement that requires them to protect your data and process it only on our instructions. Our current sub-processor list is at /legal/sub-processors.

**Business transfers.** If we are involved in a merger, acquisition, or sale of assets, your data may be transferred as part of that transaction. We will notify you before your data is transferred and becomes subject to a different privacy policy.

**Legal requirements.** We may disclose personal data if required by law, court order, or government authority, or to protect the rights, property, or safety of us, our users, or the public. We will notify you of such requests where legally permitted.

**With your consent.** We may share data with third parties for other purposes with your explicit consent.`,
  },
  {
    id: "international-transfers",
    title: "International Data Transfers",
    anchor: "international-transfers",
    inShort: "If we transfer your data outside your country, we use approved safeguards.",
    body: `**EU/EEA and UK.** If we transfer personal data from the EU/EEA or UK to countries that have not been deemed adequate by the European Commission or UK ICO, we rely on Standard Contractual Clauses (SCCs) approved by the European Commission, and the UK International Data Transfer Addendum (IDTA) for UK transfers, as the transfer mechanism.

**Switzerland.** For transfers from Switzerland, we comply with the requirements of the Swiss Federal Data Protection Act (revFDPA) and use SCCs as adapted for Swiss law.

**Data Privacy Framework.** [FILL: If ARIA participates in the EU-US Data Privacy Framework, state this here. Otherwise, remove.]

**Data residency.** [FILL: Describe available data residency options, e.g., US and EU regions, or state "We currently process data in the United States."]`,
  },
  {
    id: "retention",
    title: "Retention",
    anchor: "retention",
    inShort: "We keep your data only as long as we need it, then delete it.",
    body: `The table below summarizes how long we retain each category of data and why.`,
    table: "retentionTable",
  },
  {
    id: "security",
    title: "Security",
    anchor: "security",
    inShort: "We use industry-standard technical and organizational controls to protect your data.",
    body: `**Technical controls.** We encrypt data in transit using TLS 1.2 or higher and at rest using AES-256 or equivalent. Access to production systems is restricted to authorized personnel using multi-factor authentication.

**SOC 2 posture.** [FILL: State whether ARIA is SOC 2 Type II certified, or state "We are working toward SOC 2 Type II certification." Do not claim certification unless confirmed.]

**Information Barriers.** As described in our Terms of Service, each Customer's data is architecturally isolated at the database and inference layer.

**Access controls.** Role-based access controls limit employee access to Customer Data to those who need it to provide or support the Service.

**Incident notification.** In the event of a personal data breach that is likely to result in a risk to your rights and freedoms, we will notify the relevant supervisory authority within 72 hours of becoming aware of the breach (where required by GDPR or equivalent law), and we will notify affected individuals without undue delay where required.

**Not HIPAA-regulated.** ARIA is not a HIPAA-covered entity and is not intended for the processing of Protected Health Information (PHI). Do not upload PHI to the Service.`,
  },
  {
    id: "rights",
    title: "Your Rights by Jurisdiction",
    anchor: "rights",
    inShort: "You have rights over your data. The table below shows which rights apply where you are.",
    body: `To exercise any of the rights below, submit a request at /legal/privacy#rights or email [FILL: privacy email]. We will respond within 30 days (or the timeframe required by applicable law). We may ask you to verify your identity before processing your request.

We will not discriminate against you for exercising your privacy rights.

**CCPA "Do Not Sell or Share."** We do not sell personal data. We do not share personal data for cross-context behavioral advertising. You may still submit a "Do Not Sell or Share" request by emailing [FILL: privacy email] or by enabling the Global Privacy Control in your browser.

**Global Privacy Control (GPC).** If your browser sends a GPC signal, we automatically treat it as an opt-out of analytics and marketing cookies and do not share your data for targeted advertising.`,
    table: "rightsTable",
  },
  {
    id: "children",
    title: "Children",
    anchor: "children",
    inShort: "ARIA is not for anyone under 16.",
    body: `The Service is not directed to individuals under the age of 16 (or under 18 on any consumer-facing surface). We do not knowingly collect personal data from children. If we learn that we have collected personal data from a child under the applicable age threshold, we will delete it promptly. If you believe we have inadvertently collected such data, please contact us at [FILL: privacy email].`,
  },
  {
    id: "automated-decisions",
    title: "Automated Decision-Making",
    anchor: "automated-decisions",
    inShort: "We do not make fully automated decisions with legal or significant effects about individuals.",
    body: `ARIA uses AI to generate analyses, summaries, and recommendations. These outputs are tools to assist human decision-makers, not to replace them. We do not make fully automated decisions about individuals that produce legal effects or similarly significant effects, as defined in GDPR Article 22.

All significant outputs — such as investment memos, due diligence reports, and buyer lists — are intended to be reviewed and approved by a qualified human professional before being acted upon.

If you have questions about how AI is used in a specific feature, please contact us at [FILL: privacy email].`,
  },
  {
    id: "changes",
    title: "Changes to This Policy",
    anchor: "changes",
    inShort: "We will notify you of material changes by email and in the Service.",
    body: `We may update this Privacy Policy from time to time. For non-material changes (such as clarifications or corrections), we will update the "Last updated" date.

For material changes — those that meaningfully affect how we collect, use, or share your data — we will notify you by email and/or by a prominent notice in the Service at least 30 days before the change takes effect.

Previous versions of this Policy are archived at /legal/privacy/v[date].`,
  },
  {
    id: "contact-complaints",
    title: "Contact, Complaints, and Supervisory Authorities",
    anchor: "contact-complaints",
    inShort: "Reach us first. If we cannot resolve your concern, you have the right to complain to your local authority.",
    body: `**Contact us.** For privacy questions or to exercise your rights: [FILL: privacy/DPO email]

**EU/EEA supervisory authority.** If you are in the EU/EEA and believe we have not handled your data in accordance with GDPR, you have the right to lodge a complaint with the supervisory authority in your country of residence. A list of EU supervisory authorities is available at https://edpb.europa.eu/about-edpb/about-edpb/members_en.

**UK supervisory authority.** If you are in the UK, you may complain to the Information Commissioner's Office (ICO) at https://ico.org.uk.

**US state residents.** If you are a California resident and we do not respond to your request within the required timeframe, you may contact the California Privacy Protection Agency (CPPA) at https://cppa.ca.gov. Residents of other states may contact their state attorney general.

**Brazil.** If you are in Brazil, you may contact the Autoridade Nacional de Proteção de Dados (ANPD) at https://www.gov.br/anpd.

**Canada.** If you are in Canada, you may contact the Office of the Privacy Commissioner of Canada at https://www.priv.gc.ca.`,
  },
];
